# -*- coding: utf-8 -*-
"""Kalkulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TwZupOebm_lGIl7EbFnOVR7aA9YncXfb
"""

#function untuk kalkulasi
def calculate(num1, operator, num2):
  if operator == "+":
    return round(num1 + num2)
  elif operator == "-":
    return num1 - num2
  elif operator == "/":
    if num2 == 0:
      return "Error : tidak bisa dibagi 0"
    else:
      return round(num1 / num2, 2)
  elif operator == "x" or operator == "X":
    return num1 * num2
  else:
    return "Invalid operator"

#main program
def main():
  try:
    angka1 = float(input("Masukkan angka pertama: "))
    if angka1 > 99999:
      return "Error angka innputan 1 terlalu besar"
    operator = input("Masukkan operaor (+, -, x, /)")
    angka2 = float(input("Masukkan angka kedua: "))
    if angka2 > 99999:
      return "Error angka innputan 2 terlalu besar"
    hasil= calculate(angka1, operator, angka2)
    print("Hasil", hasil)
  except ValueError:
    print("input harus berapa angka")

main()